<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsTrimmable>false</IsTrimmable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\libs\mpv\libmpv-2.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>libmpv-2.dll</Link>
    </None>
    <None Include="..\..\libs\mpv\scripts\osc.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>libs\mpv\scripts\osc.lua</Link>
    </None>
    <None Include="..\..\libs\mpv\scripts\osc-modern.lua">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>libs\mpv\scripts\osc-modern.lua</Link>
    </None>
    <None Include="..\..\libs\mpv\fonts\material-design-iconic-font.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>libs\mpv\fonts\material-design-iconic-font.ttf</Link>
    </None>
  </ItemGroup>

</Project>
