// Executed unchanged in Chromium and the native WebView2 fixture host.
window.runReaderChecks = async function(fixtureRoot) {
    const check=(condition,message)=>{if(!condition)throw new Error(message);};
    const settle=()=>new Promise(resolve=>setTimeout(resolve,180));
    const reader=window.siloReader;
    const options={url:fixtureRoot+'/unequal.epub',format:'epub',chapters:['OPS/short.xhtml','OPS/long.xhtml'],settings:{flow:'scrolled',spread:'none'},annotations:[]};
    await reader.open(options); await settle();
    const view=()=>document.querySelector('foliate-view');
    check(await reader.go('fraction:0.50'),'fraction navigation accepted');await settle();
    check(reader.snapshot().index===1,'unequal chapter sizes: half book must be long chapter');
    const cfi=reader.snapshot().location;check(cfi.startsWith('epubcfi('),'EPUB emits CFI');
    const originalRange=view().lastLocation.range;
    const originalText=originalRange.startContainer.textContent;
    await reader.chapter(0);await reader.go(cfi);await settle();
    check(reader.snapshot().index===1,'CFI restores correct chapter');
    check(view().lastLocation.range.startContainer.textContent===originalText,'CFI restores exact text node');
    const doc=view().renderer.getContents().find(item=>item.index===1).doc;
    check(window.__bookScriptExecuted!==true,'EPUB scripts cannot execute');
    const blockedImage=doc.createElement('img');
    const blocked=await new Promise(resolve=>{blockedImage.onload=()=>resolve(false);blockedImage.onerror=()=>resolve(true);blockedImage.src='https://reader-network.invalid/track';doc.body.append(blockedImage);setTimeout(()=>resolve(false),2000);});
    check(blocked,'EPUB external image blocked by inherited CSP');blockedImage.remove();
    const target=doc.getElementById('p50').firstChild, range=doc.createRange();range.setStart(target,13);range.setEnd(target,35);
    const selection=doc.getSelection();selection.removeAllRanges();selection.addRange(range);
    const annotation=reader.selection();check(annotation?.cfi?.startsWith('epubcfi('),'selection emits CFI range');
    const resolved=view().resolveCFI(annotation.cfi).anchor(doc);check(resolved.toString().trim()===annotation.text,'shared annotation resolves exact selected text');
    const {makeBook}=await import('/vendor/foliate-js/view.js');
    const independentBook=await makeBook(new File([await (await fetch(options.url)).blob()],'fixture.epub'));
    const independentView=document.createElement('foliate-view');await independentView.open(independentBook);
    const independentDoc=await independentBook.sections[1].createDocument();
    const independentRange=independentView.resolveCFI(annotation.cfi).anchor(independentDoc);
    check(independentRange.toString().trim()===annotation.text,'desktop annotation resolves in independent WebUI-compatible renderer');
    const webRange=independentDoc.createRange();webRange.selectNodeContents(independentDoc.getElementById('p60'));
    const webAnnotation=independentView.getCFI(1,webRange);
    check(await reader.go(webAnnotation),'independently generated WebUI CFI opens in desktop');
    independentView.close();independentBook.destroy();
    await reader.annotations([{kind:'highlight',cfiRange:annotation.cfi,color:'#facc15'}]);
    check(await reader.go(annotation.cfi),'CFI range bookmark navigates');
    check(await reader.go('chapter:1;fraction:0.25'),'legacy chapter bookmark preserved');await settle();check(reader.snapshot().index===1,'legacy bookmark retains chapter');
    await reader.annotations([{kind:'highlight',location:'chapter:1;fraction:0.25',selectedText:'Paragraph 25.',color:'#facc15'}]);
    check(view().renderer.getContents().find(item=>item.index===1).overlayer.element.children.length>1,'legacy desktop highlight remains visible without rewriting stored location');
    const before=reader.snapshot().location;
    check(!await reader.go('unrecognized location'),'unknown location rejected');check(reader.snapshot().location===before,'unknown location does not jump');
    check(!await reader.go('chapter:999;fraction:0'),'out-of-range legacy rejected');
    reader.close();check(reader.snapshot()===null,'close stops progress');
    const canceled=reader.open(options);reader.close();check(await canceled===false,'close cancels in-flight open');check(reader.snapshot()===null,'canceled open cannot resurrect progress');
    let invalidFailed=false;try {await reader.open({...options,location:'unrecognized saved value'});} catch {invalidFailed=true;}
    check(invalidFailed && reader.snapshot()===null,'invalid restore suppresses progress writes');
    check(await reader.chapter(1),'explicit chapter choice recovers invalid restore');check(reader.snapshot()!==null,'explicit recovery enables progress');
    await reader.open({...options,location:'fraction:invalid',progress:.5});await settle();check(reader.snapshot().index===1,'malformed fraction uses valid saved numeric progress like WebUI');
    await reader.open({...options,location:cfi});await settle();check(reader.snapshot().index===1,'reopen resumes CFI');
    await reader.open({url:fixtureRoot+'/four-pages.pdf',format:'pdf',settings:{spread:'none'}});await settle();
    check(reader.snapshot().count===4,'PDF has four observable pages');
    check(await reader.go('chapter:0;fraction:0'),'legacy desktop PDF location opens at original beginning');
    await reader.chapter(2);await settle();const pdf=reader.snapshot();check(pdf.index===2,'PDF navigates page three');check(pdf.progress>0,'PDF emits progress');
    check(pdf.location.startsWith('epubcfi(')||pdf.location.startsWith('fraction:'),'PDF emits shared location');
    await reader.chapter(0);const pdfOk=await reader.go(pdf.location);await settle();check(reader.snapshot().index===2,'PDF bookmark restores page three '+JSON.stringify({pdf,pdfOk,current:reader.snapshot()}));
    reader.close();await reader.open({url:fixtureRoot+'/four-pages.pdf',format:'pdf',location:pdf.location,settings:{spread:'none'}});await settle();check(reader.snapshot().index===2,'PDF reopen resumes page three');
    reader.close();
    return {epubCfi:cfi,annotationCfi:annotation.cfi,pdfLocation:pdf.location,pdfProgress:pdf.progress,checks:29};
};
