namespace SiloPlayer.Tests;
public sealed class AdminPolicyParitySourceTests
{
 [Fact] public void PolicyWorkspaceUsesCurrentCapabilityAndAdminContracts(){var api=Read("src","SiloPlayer.Core","Api","AdminApi.cs");foreach(var value in new[]{"/api/v1/policy/capability","/admin/policy/vendor","/admin/policy/documents","/versions","/activate","/enabled","/validate","/simulate","/decisions"})Assert.Contains(value,api);}
 [Fact] public void PolicyNavigationIsCapabilityGated(){var shell=Read("src","SiloPlayer","Views","Admin","AdminShellPage.xaml.cs");Assert.Contains("capability.Enabled && capability.EditorAvailable",shell);Assert.Contains("if (_policyAvailable)",shell);Assert.Contains("typeof(AdminPolicyPage)",shell);}
 [Fact] public void PolicyPageProvidesOverridesBaselineSimulationVersionsAndDecisions(){var page=Read("src","SiloPlayer","Views","Admin","AdminPolicyPage.xaml");foreach(var value in new[]{"Overrides","Baseline","Decision Log","Version history","Validate draft","Save as version","Re-validate","Simulate this policy","User ID","Allowed","Denied","Silo decides the baseline","Your overrides narrow it","Every decision is logged","RFC3339 or blank"})Assert.Contains(value,page);}
 [Fact] public void PolicyLifecycleKeepsValidateSaveAndActivationAsSeparateServerMutations(){var viewModel=Read("src","SiloPlayer","ViewModels","Admin","AdminPolicyViewModel.cs");var page=Read("src","SiloPlayer","Views","Admin","AdminPolicyPage.xaml.cs");foreach(var value in new[]{"ValidateDraftAsync","SaveVersionAsync","ActivateDraftAsync","Validation passed — the draft compiles.","Saved v"})Assert.Contains(value,viewModel);Assert.Contains("Go live",page);Assert.DoesNotContain("saved and activated",viewModel,StringComparison.OrdinalIgnoreCase);}
 [Fact] public void PolicyVersionEndpointsUseOpaqueVersionIds(){var api=Read("src","SiloPlayer.Core","Api","AdminApi.cs");var page=Read("src","SiloPlayer","Views","Admin","AdminPolicyPage.xaml.cs");Assert.Contains("long versionId",api);Assert.Contains("version.Id);",page);Assert.DoesNotContain("GetPolicyVersionAsync(ViewModel.SelectedDocument.Id, version.VersionNumber)",page);}
 [Fact] public void PolicyOverridesAreGroupedByDomainAndDecisionLogIsPaged(){var page=Read("src","SiloPlayer","Views","Admin","AdminPolicyPage.xaml.cs");foreach(var value in new[]{"BuildDomainCard","DomainPresentation","New override","Make live","NextDecisionPageAsync","PreviousDecisionPageAsync"})Assert.Contains(value,page);}
 [Fact] public void PolicyPageReflowsAndContainsWideDecisionData(){var markup=Read("src","SiloPlayer","Views","Admin","AdminPolicyPage.xaml");var page=Read("src","SiloPlayer","Views","Admin","AdminPolicyPage.xaml.cs");foreach(var value in new[]{"PolicyPageShell","PipelineGrid","VendorGrid","DecisionFilterGrid","HorizontalScrollBarVisibility=\"Auto\"","SelectedVersionSource"})Assert.Contains(value,markup);Assert.Contains("ApplyResponsiveLayout",page);}
 [Fact] public void PolicyUsesDomainDecisionChoicesAndGuardsFailedMutations(){var markup=Read("src","SiloPlayer","Views","Admin","AdminPolicyPage.xaml");var page=Read("src","SiloPlayer","Views","Admin","AdminPolicyPage.xaml.cs");Assert.Contains("DecisionFilterCombo",markup);Assert.Contains("silo.{domain}.decision",page);Assert.Contains("ViewVersion_Click",page);Assert.Contains("if (!string.IsNullOrWhiteSpace(ViewModel.ErrorMessage)) return;",page);Assert.Contains("ToastService",page);}
 static string Read(params string[] parts){var d=AppContext.BaseDirectory;while(!string.IsNullOrEmpty(d)&&!File.Exists(Path.Combine(d,"SiloPlayer.sln")))d=Directory.GetParent(d)?.FullName??"";if(string.IsNullOrEmpty(d))throw new InvalidOperationException();return File.ReadAllText(Path.Combine([d,..parts]));}
}
